### PR TITLE
Changing the package structure

### PR DESCRIPTION
**Pull request by UzEE**
Moved all the stylesheet files into a new ```css``` directory to address #13 and #7, as well as improving compatibility with other projects.

### CODE REVIEW

**Comment by choffmeister** [comment]
Looks good. Can you please squash a little and remove the version bumping? I will do that before merging into master.

**Comment by choffmeister** [comment]
Did the squashing for you. Merged this with 372fa6e695d59b7b14b1ed714557f6a2e9825aab

**Comment by choffmeister** [comment]
Released as [v0.4.0](https://github.com/choffmeister/roboto-fontface-bower/releases/tag/v0.4.0)

**Comment by UzEE** [comment]
Thanks :)

**Comment by choffmeister** [comment]
You're welcome! Thanks for the PR

**Pull request closed without merging**
