### PR TITLE
Fixes for fonts folders names and common roboto css file paths

### PR DESCRIPTION
**Pull request by Badou90**
1) Changed folders names to names in capitalized
2) Changed paths in roboto-fontface.css file to new folders

Don't know why you made folders in lowercase but in usual css files paths were different (capitalized in condesed and lowercase in usual font)

### CODE REVIEW

**Comment by RoM4iK** [comment]
No updates in sass/less

**Comment by paralin** [comment]
Seriously, let's get this merged, @choffmeister this is a really simple fix and works well.

**Comment by choffmeister** [comment]
Sorry had lots of stuff to do the last weeks.

Thanks for the fix. Interesting that nobody noticed this bug before.

**Comment by choffmeister** [comment]
Release as roboto-fontface@0.6.0

**Pull request merged**
