### PR TITLE
EOT Files Fix

### LINKED ISSUE #16: Bad EOT files
This repo has issues in .EOT files:
http://stackoverflow.com/questions/9627899/why-is-ie8-not-loading-my-eot-files

### PR DESCRIPTION
**Pull request by corneadoug**
Created the .eot files from http://www.fontsquirrel.com/tools/webfont-generator.
It fix the error: CSS3111: @font-face encountered unknown error

### CODE REVIEW

**Comment by corneadoug** [comment]
Hi @choffmeister 
Can you tell me if there is anything to do more in this PR?

**Comment by choffmeister** [comment]
Sry, was on vacation. I cannot test, if the EOT files really work. But I will just trust you, now :)

**Comment by choffmeister** [comment]
@corneadoug Released as https://github.com/choffmeister/roboto-fontface-bower/releases/tag/v0.4.3

**Comment by corneadoug** [comment]
Thanks, now I can use the bower dependency again :)

**Pull request merged**
