### PR TITLE
Update fonts to version 2.138

### LINKED ISSUE #52: Font differ with font from google
Hello, 
I add this package into my project instead fonts from google 
But height of letters little differ. (see red arrows on screenshot).   
Left - `roboto-fontface`
include into project with:   
```
@import url("../../node_modules/roboto-fontface/css/roboto/roboto-fontface.css");
```
Right - fonts from google
include into project with:   
```
@import url(http://fonts.googleapis.com/css?family=Roboto:100,100italic,200,300,300ita‌​lic,400,400italic,500,500italic,700,700italic,900italic,900);
```
image

any ideas?

### PR DESCRIPTION
**Pull request by jdanil**
Fixes #52 (and possibly #44).

Fonts were last updated in February 2015.
https://github.com/Purush0th/roboto-fontface-bower/commit/9d894078a2cbc1706ffd7b0bedc842b7fa0c8d98

TTF files from:
* https://fonts.google.com/specimen/Roboto
* https://fonts.google.com/specimen/Roboto+Condensed
* https://fonts.google.com/specimen/Roboto+Slab

Converted font files from:
* https://google-webfonts-helper.herokuapp.com/fonts/roboto
* https://google-webfonts-helper.herokuapp.com/fonts/roboto-condensed
* https://google-webfonts-helper.herokuapp.com/fonts/roboto-slab

roboto-diff

### CODE REVIEW

**Comment by jdanil** [comment]
@choffmeister

**Comment by choffmeister** [comment]
@jdanil  Sorry for delay. Will merge this tonight and release it as new minor version

**Comment by jdanil** [comment]
All good. Thanks mate.

**Comment by choffmeister** [comment]
@jdanil Since the SVG files have been deleted, you must also remove it from the CSS.

**Comment by jdanil** [comment]
@choffmeister I don't think any of the SVG files were deleted.
They appear differently to the other files changed as they are binary files while the SVGs are represented as XMLs.
All the red for the SVGs is because the updated files are smaller, so there are less lines.
All the SVG files should still be there.

**Comment by choffmeister** [comment]
@jdanil True. My bad

**Comment by choffmeister** [comment]
@jdanil Released as `0.9.0`

**Comment by jdanil** [comment]
Thanks @choffmeister!

**Pull request merged**
